package sv.edu.udb.www.model.entity;
// Generated 09-27-2020 09:55:08 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Incidentes generated by hbm2java
 */
public class Incidentes  implements java.io.Serializable {


     private Integer idIncidentes;
     private Inventario inventario;
     private Date fechaIncidente;
     private String nombreVehiculo;
     private String descripcionIncidente;
     private String descripcionReporte;
     private String estatusIncidente;
     private byte[] imagenIncidentes;
     private int idRegistroVehiculo;
     private int idInventario;

    public Incidentes() {
    }

    public Incidentes(Inventario inventario, Date fechaIncidente, String nombreVehiculo, String descripcionIncidente, String descripcionReporte, String estatusIncidente, byte[] imagenIncidentes, int idRegistroVehiculo, int idInventario) {
       this.inventario = inventario;
       this.fechaIncidente = fechaIncidente;
       this.nombreVehiculo = nombreVehiculo;
       this.descripcionIncidente = descripcionIncidente;
       this.descripcionReporte = descripcionReporte;
       this.estatusIncidente = estatusIncidente;
       this.imagenIncidentes = imagenIncidentes;
       this.idRegistroVehiculo = idRegistroVehiculo;
       this.idInventario = idInventario;
    }
   
    public Integer getIdIncidentes() {
        return this.idIncidentes;
    }
    
    public void setIdIncidentes(Integer idIncidentes) {
        this.idIncidentes = idIncidentes;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public Date getFechaIncidente() {
        return this.fechaIncidente;
    }
    
    public void setFechaIncidente(Date fechaIncidente) {
        this.fechaIncidente = fechaIncidente;
    }
    public String getNombreVehiculo() {
        return this.nombreVehiculo;
    }
    
    public void setNombreVehiculo(String nombreVehiculo) {
        this.nombreVehiculo = nombreVehiculo;
    }
    public String getDescripcionIncidente() {
        return this.descripcionIncidente;
    }
    
    public void setDescripcionIncidente(String descripcionIncidente) {
        this.descripcionIncidente = descripcionIncidente;
    }
    public String getDescripcionReporte() {
        return this.descripcionReporte;
    }
    
    public void setDescripcionReporte(String descripcionReporte) {
        this.descripcionReporte = descripcionReporte;
    }
    public String getEstatusIncidente() {
        return this.estatusIncidente;
    }
    
    public void setEstatusIncidente(String estatusIncidente) {
        this.estatusIncidente = estatusIncidente;
    }
    public byte[] getImagenIncidentes() {
        return this.imagenIncidentes;
    }
    
    public void setImagenIncidentes(byte[] imagenIncidentes) {
        this.imagenIncidentes = imagenIncidentes;
    }
    public int getIdRegistroVehiculo() {
        return this.idRegistroVehiculo;
    }
    
    public void setIdRegistroVehiculo(int idRegistroVehiculo) {
        this.idRegistroVehiculo = idRegistroVehiculo;
    }
    public int getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(int idInventario) {
        this.idInventario = idInventario;
    }




}


