package sv.edu.udb.www.model.entity;
// Generated 09-27-2020 09:55:08 PM by Hibernate Tools 4.3.1



/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private Integer idInventario;
     private GastosAdicionales gastosAdicionales;
     private String nombreVehiculo;
     private String medidaUso;
     private String estadoInventario;
     private String tipoVehiculo;
     private String nombreTaller;
     private int idRegistroVehiculo;
     private int idTallerMecanico;
     private Incidentes incidentes;
     private TallerMecanico tallerMecanico;

    public Inventario() {
    }

	
    public Inventario(GastosAdicionales gastosAdicionales, String nombreVehiculo, String medidaUso, String estadoInventario, String tipoVehiculo, String nombreTaller, int idRegistroVehiculo, int idTallerMecanico) {
        this.gastosAdicionales = gastosAdicionales;
        this.nombreVehiculo = nombreVehiculo;
        this.medidaUso = medidaUso;
        this.estadoInventario = estadoInventario;
        this.tipoVehiculo = tipoVehiculo;
        this.nombreTaller = nombreTaller;
        this.idRegistroVehiculo = idRegistroVehiculo;
        this.idTallerMecanico = idTallerMecanico;
    }
    public Inventario(GastosAdicionales gastosAdicionales, String nombreVehiculo, String medidaUso, String estadoInventario, String tipoVehiculo, String nombreTaller, int idRegistroVehiculo, int idTallerMecanico, Incidentes incidentes, TallerMecanico tallerMecanico) {
       this.gastosAdicionales = gastosAdicionales;
       this.nombreVehiculo = nombreVehiculo;
       this.medidaUso = medidaUso;
       this.estadoInventario = estadoInventario;
       this.tipoVehiculo = tipoVehiculo;
       this.nombreTaller = nombreTaller;
       this.idRegistroVehiculo = idRegistroVehiculo;
       this.idTallerMecanico = idTallerMecanico;
       this.incidentes = incidentes;
       this.tallerMecanico = tallerMecanico;
    }
   
    public Integer getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(Integer idInventario) {
        this.idInventario = idInventario;
    }
    public GastosAdicionales getGastosAdicionales() {
        return this.gastosAdicionales;
    }
    
    public void setGastosAdicionales(GastosAdicionales gastosAdicionales) {
        this.gastosAdicionales = gastosAdicionales;
    }
    public String getNombreVehiculo() {
        return this.nombreVehiculo;
    }
    
    public void setNombreVehiculo(String nombreVehiculo) {
        this.nombreVehiculo = nombreVehiculo;
    }
    public String getMedidaUso() {
        return this.medidaUso;
    }
    
    public void setMedidaUso(String medidaUso) {
        this.medidaUso = medidaUso;
    }
    public String getEstadoInventario() {
        return this.estadoInventario;
    }
    
    public void setEstadoInventario(String estadoInventario) {
        this.estadoInventario = estadoInventario;
    }
    public String getTipoVehiculo() {
        return this.tipoVehiculo;
    }
    
    public void setTipoVehiculo(String tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }
    public String getNombreTaller() {
        return this.nombreTaller;
    }
    
    public void setNombreTaller(String nombreTaller) {
        this.nombreTaller = nombreTaller;
    }
    public int getIdRegistroVehiculo() {
        return this.idRegistroVehiculo;
    }
    
    public void setIdRegistroVehiculo(int idRegistroVehiculo) {
        this.idRegistroVehiculo = idRegistroVehiculo;
    }
    public int getIdTallerMecanico() {
        return this.idTallerMecanico;
    }
    
    public void setIdTallerMecanico(int idTallerMecanico) {
        this.idTallerMecanico = idTallerMecanico;
    }
    public Incidentes getIncidentes() {
        return this.incidentes;
    }
    
    public void setIncidentes(Incidentes incidentes) {
        this.incidentes = incidentes;
    }
    public TallerMecanico getTallerMecanico() {
        return this.tallerMecanico;
    }
    
    public void setTallerMecanico(TallerMecanico tallerMecanico) {
        this.tallerMecanico = tallerMecanico;
    }




}


