package sv.edu.udb.www.model.entity;
// Generated 09-27-2020 09:55:08 PM by Hibernate Tools 4.3.1



/**
 * RegistroProveedor generated by hbm2java
 */
public class RegistroProveedor  implements java.io.Serializable {


     private Integer idRegistroProveedor;
     private Proveedores proveedores;
     private String nombreComercial;
     private int telefono;
     private String direccion;
     private String municipio;
     private String departamento;
     private String pais;
     private String personaContacto;
     private int telefonoContacto;
     private int idProveedores;
     private String correoConacto;

    public RegistroProveedor() {
    }

    public RegistroProveedor(Proveedores proveedores, String nombreComercial, int telefono, String direccion, String municipio, String departamento, String pais, String personaContacto, int telefonoContacto, int idProveedores, String correoConacto) {
       this.proveedores = proveedores;
       this.nombreComercial = nombreComercial;
       this.telefono = telefono;
       this.direccion = direccion;
       this.municipio = municipio;
       this.departamento = departamento;
       this.pais = pais;
       this.personaContacto = personaContacto;
       this.telefonoContacto = telefonoContacto;
       this.idProveedores = idProveedores;
       this.correoConacto = correoConacto;
    }
   
    public Integer getIdRegistroProveedor() {
        return this.idRegistroProveedor;
    }
    
    public void setIdRegistroProveedor(Integer idRegistroProveedor) {
        this.idRegistroProveedor = idRegistroProveedor;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getPersonaContacto() {
        return this.personaContacto;
    }
    
    public void setPersonaContacto(String personaContacto) {
        this.personaContacto = personaContacto;
    }
    public int getTelefonoContacto() {
        return this.telefonoContacto;
    }
    
    public void setTelefonoContacto(int telefonoContacto) {
        this.telefonoContacto = telefonoContacto;
    }
    public int getIdProveedores() {
        return this.idProveedores;
    }
    
    public void setIdProveedores(int idProveedores) {
        this.idProveedores = idProveedores;
    }
    public String getCorreoConacto() {
        return this.correoConacto;
    }
    
    public void setCorreoConacto(String correoConacto) {
        this.correoConacto = correoConacto;
    }




}


