package sv.edu.udb.www.model.entity;
// Generated 09-27-2020 09:55:08 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private GastosAdicionales gastosAdicionales;
     private String user;
     private String password;
     private String nombreUsuario;
     private String correoUsuario;
     private String tipoUsuario;
     private int correlativo;

    public Usuario() {
    }

    public Usuario(GastosAdicionales gastosAdicionales, String user, String password, String nombreUsuario, String correoUsuario, String tipoUsuario, int correlativo) {
       this.gastosAdicionales = gastosAdicionales;
       this.user = user;
       this.password = password;
       this.nombreUsuario = nombreUsuario;
       this.correoUsuario = correoUsuario;
       this.tipoUsuario = tipoUsuario;
       this.correlativo = correlativo;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public GastosAdicionales getGastosAdicionales() {
        return this.gastosAdicionales;
    }
    
    public void setGastosAdicionales(GastosAdicionales gastosAdicionales) {
        this.gastosAdicionales = gastosAdicionales;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getCorreoUsuario() {
        return this.correoUsuario;
    }
    
    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public int getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(int correlativo) {
        this.correlativo = correlativo;
    }




}


